class FoodRecipes {
  String name;
  String imageAsset;
  String description;
  String rating;
  String time;
  String porsi;
  String kalori;
  String dificult;
  List<String> ingredients;
  List<String> instructions;

  FoodRecipes({
    required this.name,
    required this.imageAsset,
    required this.description,
    required this.rating,
    required this.time,
    required this.porsi,
    required this.kalori,
    required this.dificult,
    required this.ingredients,
    required this.instructions,
  });
}

var foodRecipesList = [
  FoodRecipes(
    name: "Nasi Goreng",
    imageAsset: "assets/images/nasgor.jpg",
    description:
    "Hidangan nasi goreng khas Indonesia yang kaya rasa, sering disajikan dengan telur, ayam, dan kerupuk.",
    rating: "4.8",
    time: "25",
    porsi: "2",
    kalori: "450",
    dificult: "Mudah",
    ingredients: [
      '2 piring nasi putih (sisa kemarin lebih baik)',
      '1 butir telur',
      '2 siung bawang putih, cincang',
      '3 siung bawang merah, iris tipis',
      '1/2 sendok teh terasi (opsional)',
      '2 sendok makan kecap manis',
      '1 sendok teh saus sambal (opsional)',
      'Garam dan merica secukupnya',
      'Minyak goreng secukupnya',
      'Topping: ayam suwir, sosis, bakso, kerupuk, atau acar',
    ],
    instructions: [
      'Panaskan minyak, tumis bawang putih, bawang merah, dan terasi hingga harum.',
      'Masukkan telur, orak-arik hingga matang.',
      'Masukkan nasi, aduk rata. Tambahkan kecap manis, saus sambal, garam, dan merica.',
      'Aduk terus hingga bumbu tercampur rata dan nasi mulai sedikit kering.',
      'Tambahkan topping sesuai selera, aduk sebentar.',
      'Sajikan hangat dengan kerupuk dan acar.',
    ],
  ),
  FoodRecipes(
    name: "Rendang Sapi",
    imageAsset: "assets/images/rendang.jpg",
    description:
    'Rendang adalah masakan daging khas Minangkabau yang dimasak dengan santan dan bumbu rempah-rempah yang kaya.',
    rating: "4,9",
    time: "240",
    porsi: "6",
    kalori: "550",
    dificult: "Sulit",
    ingredients: [
      '1 kg daging sapi',
      '1 liter santan kental',
      '500 ml santan encer',
      'Bumbu halus:',
      '15 butir bawang merah',
      '8 siung bawang putih',
      '2 cm jahe',
      '2 cm kunyit',
      '2 cm lengkuas',
      '2 batang serai, memarkan',
      '4 lembar daun jeruk',
      '2 lembar daun kunyit',
    ],
    instructions: [
      'Haluskan semua bumbu halus.',
      'Masukkan daging sapi, bumbu halus, dan santan encer ke dalam wajan. Masak hingga santan mendidih sambil diaduk.',
      'Setelah santan encer menyusut, masukkan santan kental. Masak terus dengan api kecil sambil sesekali diaduk.',
      'Masak hingga santan mengering dan bumbu meresap sempurna. Proses ini membutuhkan waktu lama hingga daging empuk dan rendang berwarna gelap.',
    ],
  ),
  FoodRecipes(
    name: "Sate Ayam",
    imageAsset: "assets/images/sate-ayam.jpg",
    description:
    'Sate ayam adalah makanan khas Indonesia yang terbuat dari potongan daging ayam yang ditusuk dengan tusuk sate, dibakar, dan disajikan dengan bumbu kacang.',
    rating: "4.7",
    time: "45",
    porsi: "4",
    kalori: "400",
    dificult: "Sedang",
    ingredients: [
      '500 gr dada ayam fillet',
      '1 sendok makan kecap manis',
      '1/2 sendok teh ketumbar bubuk',
      '1/4 sendok teh lada bubuk',
      'Tusuk sate secukupnya',
      'Bumbu kacang:',
      '150 gr kacang tanah goreng',
      '2 siung bawang putih',
      '2 buah cabai merah',
      'Garam, gula, dan air secukupnya',
    ],
    instructions: [
      'Potong ayam berbentuk dadu. Campur dengan kecap manis, ketumbar, dan lada. Diamkan 15 menit.',
      'Tusuk ayam pada tusuk sate, sekitar 4-5 potong per tusuk.',
      'Bakar sate di atas arang atau teflon hingga matang, sesekali dioles sisa bumbu.',
      'Untuk bumbu kacang, haluskan kacang, bawang putih, dan cabai. Masak dengan air hingga mengental. Bumbui dengan garam dan gula.',
      'Sajikan sate dengan bumbu kacang, irisan bawang merah, dan nasi atau lontong.',
    ],
  ),
  FoodRecipes(
    name: "Gado-gado",
    imageAsset: "assets/images/gado-gado.jpg",
    description:
    'Gado-gado adalah salad khas Indonesia yang terdiri dari sayuran rebus, telur, kentang, tahu, tempe, dan disiram dengan bumbu kacang.',
    rating: "4.6",
    time: "30",
    porsi: "2",
    kalori: "350",
    dificult: "Mudah",
    ingredients: [
      '100 gr kacang panjang, potong-potong',
      '100 gr kol, iris kasar',
      '100 gr tauge',
      '2 buah kentang, rebus',
      '2 buah telur rebus',
      'Tahu dan tempe goreng secukupnya',
      'Bumbu kacang:',
      '150 gr kacang tanah goreng',
      '3 siung bawang putih',
      'Garam, gula merah, dan air asam jawa secukupnya',
    ],
    instructions: [
      'Rebus semua sayuran hingga matang, tiriskan.',
      'Susun sayuran, telur, kentang, tahu, dan tempe di piring.',
      'Untuk bumbu, haluskan kacang, bawang putih, dan bumbu lain. Tambahkan air panas hingga kekentalan yang diinginkan.',
      'Siram bumbu kacang di atas sayuran. Sajikan dengan kerupuk atau emping.',
    ],
  ),
  FoodRecipes(
    name: "Soto Ayam",
    imageAsset: "assets/images/soto-ayam.jpg",
    description:
    'Soto ayam adalah sup ayam berkuah kuning khas Indonesia dengan bumbu rempah-rempah yang hangat dan kaya rasa.',
    rating: "4.5",
    time: "60",
    porsi: "4",
    kalori: "300",
    dificult: "Sedang",
    ingredients: [
      '500 gr dada ayam',
      '1.5 liter air',
      '2 lembar daun salam',
      '2 batang serai',
      '2 cm lengkuas',
      'Bumbu halus:',
      '5 siung bawang putih',
      '5 butir bawang merah',
      '3 cm kunyit',
      '1 sendok teh ketumbar',
    ],
    instructions: [
      'Rebus ayam hingga matang, angkat, suwir-suwir. Gunakan air rebusan sebagai kaldu.',
      'Haluskan bumbu, tumis hingga harum. Masukkan daun salam, serai, dan lengkuas.',
      'Masukkan bumbu ke dalam kaldu. Masak hingga mendidih dan bumbu meresap.',
      'Sajikan dengan nasi, suwiran ayam, tauge, seledri, dan bawang goreng.',
    ],
  ),
  FoodRecipes(
    name: "Sushi",
    imageAsset: "assets/images/sushi.jpg",
    description:
    'Sushi adalah makanan khas Jepang yang terbuat dari nasi yang dikepal dengan lauk pauk berupa makanan laut, daging, atau sayuran mentah atau matang.',
    rating: "4.7",
    time: "45",
    porsi: "2",
    kalori: "300",
    dificult: "Sulit",
    ingredients: [
      '200 gr beras Jepang',
      '250 ml air',
      '3 sendok makan cuka beras',
      '1 sendok teh gula',
      '1/2 sendok teh garam',
      'Nori (rumput laut)',
      'Isian: irisan ikan salmon/tuna, timun, alpukat',
    ],
    instructions: [
      'Masak beras Jepang hingga matang. Campur cuka, gula, dan garam, lalu campurkan ke nasi selagi hangat.',
      'Letakkan nori di atas makisu (alas bambu). Ratakan nasi di atasnya.',
      'Susun isian di tengah nasi. Gulung dengan hati-hati hingga padat.',
      'Potong sushi dengan pisau tajam yang dibasahi air. Sajikan dengan kecap asin dan wasabi.',
    ],
  ),
  FoodRecipes(
    name: "Ramen",
    imageAsset: "assets/images/ramen.jpg",
    description:
    'Ramen adalah mie kuah khas Jepang yang disajikan dengan kuah kaldu yang gurih dan topping seperti irisan daging, telur rebus, dan sayuran.',
    rating: "4.8",
    time: "40",
    porsi: "1",
    kalori: "Sedang",
    dificult: "Sedang",
    ingredients: [
      '1 bungkus mie ramen',
      '200 gr daging ayam atau babi',
      '1 butir telur rebus',
      '2 lembar nori',
      'Tauge, daun bawang, dan jagung secukupnya',
      'Bumbu kuah:',
      '500 ml kaldu ayam atau dashi',
      '1 sendok makan kecap asin',
      '1/2 sendok teh minyak wijen',
    ],
    instructions: [
      'Rebus mie ramen hingga matang, tiriskan.',
      'Rebus daging hingga matang, angkat, iris tipis.',
      'Didihkan kaldu, tambahkan kecap asin dan minyak wijen.',
      'Susun mie dalam mangkuk, siram dengan kuah panas. Tambahkan irisan daging, telur, dan topping lainnya.',
    ],
  ),
  FoodRecipes(
    name: "Tempura",
    imageAsset: "assets/images/tempura.jpg",
    description:
    'Tempura adalah makanan khas Jepang berupa makanan laut atau sayuran yang dicelup ke adonan tepung dan digoreng.',
    rating: "4.6",
    time: "30",
    porsi: "2",
    kalori: "450",
    dificult: "Sedang",
    ingredients: [
      '200 gr udang',
      '100 gr sayuran (brokoli, wortel, terong)',
      'Tepung tempura instan',
      'Air es',
      'Minyak untuk menggoreng',
      'Saus tempura (tsuyu)',
    ],
    instructions: [
      'Siapkan adonan tempura dengan mencampur tepung tempura instan dan air es sesuai petunjuk kemasan.',
      'Celupkan udang dan sayuran ke dalam adonan, pastikan tidak terlalu tebal.',
      'Panaskan minyak, goreng tempura hingga keemasan. Angkat dan tiriskan.',
      'Sajikan tempura selagi hangat dengan saus tempura (tsuyu).',
    ],
  ),
  FoodRecipes(
    name: "Spaghetti Carbonara",
    imageAsset: "assets/images/spaghetti.jpg",
    description:
    'Spaghetti Carbonara adalah pasta khas Italia dengan saus krim dari telur, keju parmesan, dan guanciale (daging babi asap).',
    rating: "4.7",
    time: "25",
    porsi: "2",
    kalori: "600",
    dificult: "Sedang",
    ingredients: [
      '200 gr spaghetti',
      '100 gr guanciale atau bacon, potong dadu',
      '2 butir kuning telur',
      '50 gr keju parmesan parut',
      'Garam dan lada hitam secukupnya',
    ],
    instructions: [
      'Rebus spaghetti hingga al dente. Sisihkan air rebusan pasta.',
      'Tumis guanciale/bacon hingga renyah. Sisihkan minyaknya.',
      'Dalam mangkuk, campur kuning telur, keju parmesan, lada hitam, dan sedikit air rebusan pasta.',
      'Masukkan spaghetti panas ke dalam mangkuk, aduk cepat hingga saus mengental. Tambahkan daging dan aduk rata.',
      'Sajikan segera dengan taburan keju parmesan.',
    ],
  ),
  FoodRecipes(
    name: "Pizza Margherita",
    imageAsset: "assets/images/pizza.jpg",
    description:
    'Pizza Margherita adalah pizza klasik Italia dengan topping sederhana tomat, mozzarella, dan basil.',
    rating: "4.5",
    time: "40",
    porsi: "3",
    kalori: "550",
    dificult: "Sedang",
    ingredients: [
      '1 adonan pizza siap pakai',
      '100 gr saus tomat',
      '150 gr keju mozzarella, iris',
      'Beberapa lembar daun basil',
      'Minyak zaitun',
    ],
    instructions: [
      'Letakkan adonan pizza di loyang. Ratakan saus tomat di atasnya.',
      'Susun irisan mozzarella di atas saus.',
      'Panggang dalam oven yang sudah dipanaskan hingga keju meleleh dan pinggiran pizza kecoklatan.',
      'Keluarkan dari oven, taburi daun basil dan sedikit minyak zaitun.',
    ],
  ),
];
